// Consumer-side file. Creates worker and defines what to do when a monthly-review job is received.

import {
    DataQualityLevel,
    MonthlyReview,
    MonthlyReviewStatus,
} from "@prisma/client";
import { Job, Worker } from "bullmq";
import { prisma } from "../../config/db";
import { bullMqConnection } from "../../config/bullmq";
import {
    MONTHLY_REVIEW_QUEUE_NAME,
    MonthlyReviewJobData,
} from "../monthlyReview.job";

const formatWorkerError = (error: Error) => ({
    name: error.name,
    message: error.message || "No error message provided",
    stack: error.stack,
});

const buildFakeMonthlyReviewResult = (review: MonthlyReview) => {
    return {
        executiveSummary:
            "This is a temporary monthly review generated by the worker. Real aggregation and AI interpretation will be added next.",
        financialHealthScore: {
            score: 70,
            label: "GOOD",
            reasons: [
                "The async worker successfully processed this review.",
                "Financial metrics are placeholder values for now.",
            ],
        },
        keyMetrics: {
            totalIncome: 0,
            totalExpense: 0,
            netSavings: 0,
            savingsRate: null,
            expenseToIncomeRatio: null,
            transactionCount: review.transactionCount,
        },
        comparison: {
            incomeChangePercent: null,
            expenseChangePercent: null,
            savingsChangePercent: null,
            summary:
                "Previous month comparison will be calculated in the aggregation step.",
        },
        spendingBehaviorPatterns: [
            "Spending behavior patterns will be generated after database aggregation is implemented.",
        ],
        unusualSpendingOrRiskSignals: [],
        savingsQuality: {
            summary:
                "Savings quality will be evaluated after real income and expense totals are available.",
            rating: "MEDIUM",
        },
        suggestedBudgetTargets: [],
        nextMonthActionPlan: [
            "Review this placeholder report only as a worker lifecycle test.",
        ],
    };
};

// Processes monthly review jobs from Redis.
// For now this saves a fake result so we can test DB status transitions before adding aggregation or Gemini.
const processMonthlyReviewJob = async (job: Job<MonthlyReviewJobData>) => {
    console.log("Monthly review job received", {
        jobId: job.id,
        reviewId: job.data.reviewId,
        userId: job.data.userId,
    });

    // Always read PostgreSQL before doing work. Redis/BullMQ is only the task runner.
    const review = await prisma.monthlyReview.findFirst({
        where: {
            id: job.data.reviewId,
            userId: job.data.userId,
        },
    });

    // Skip job if review not found in DB.
    if (!review) {
        console.warn(
            "Monthly review job skipped because review row was not found",
            {
                jobId: job.id,
                reviewId: job.data.reviewId,
                userId: job.data.userId,
            },
        );

        return {
            skipped: true,
            reason: "REVIEW_NOT_FOUND",
        };
    }

    // Skip job if status is not PENDING.
    if (review.status !== MonthlyReviewStatus.PENDING) {
        console.warn(
            "Monthly review job skipped because review is not pending",
            {
                jobId: job.id,
                reviewId: review.id,
                status: review.status,
            },
        );

        return {
            skipped: true,
            reason: "REVIEW_NOT_PENDING",
            status: review.status,
        };
    }

    // Move from PENDING to PROCESSING only if it is still pending.
    // This protects us from duplicate/stale jobs doing the same work twice.
    const processingUpdate = await prisma.monthlyReview.updateMany({
        where: {
            id: review.id,
            userId: review.userId,
            status: MonthlyReviewStatus.PENDING,
        },
        data: {
            status: MonthlyReviewStatus.PROCESSING,
            errorMessage: null,
            completedAt: null,
        },
    });

    // If no row was updated, another worker/process changed the review status after our initial read.
    // In that case this job is stale, so we skip it instead of generating the same review twice.
    if (processingUpdate.count === 0) {
        console.warn(
            "Monthly review job skipped because status changed before processing",
            {
                jobId: job.id,
                reviewId: review.id,
            },
        );

        return {
            skipped: true,
            reason: "STATUS_CHANGED",
        };
    }

    // Create fake result.
    const result = buildFakeMonthlyReviewResult(review);

    // Update monthly review with fake result and other properties.
    await prisma.monthlyReview.update({
        where: {
            id: review.id,
        },
        data: {
            status: MonthlyReviewStatus.COMPLETED,
            dataQualityLevel: DataQualityLevel.LOW,
            result,
            errorMessage: null,
            completedAt: new Date(),
        },
    });

    return {
        completed: true,
        reviewId: review.id,
    };
};

// Create worker that listens to the monthly-review queue and for each job runs processMonthlyReviewJob.
// NOTE: Dequeueing is handled internally by the worker.
export const monthlyReviewWorker = new Worker<MonthlyReviewJobData>(
    MONTHLY_REVIEW_QUEUE_NAME,
    processMonthlyReviewJob,
    {
        connection: bullMqConnection,
        // Worker can process up to 2 jobs at the same time.
        concurrency: 2,
    },
);

// Log when worker is ready.
monthlyReviewWorker.on("ready", () => {
    console.log("Monthly review worker ready");
});

// Log successful jobs.
monthlyReviewWorker.on("completed", (job) => {
    console.log("Monthly review job completed", {
        jobId: job.id,
        reviewId: job.data.reviewId,
    });
});

// Log failed jobs.
monthlyReviewWorker.on("failed", (job, error) => {
    console.error("Monthly review job failed", {
        jobId: job?.id,
        reviewId: job?.data.reviewId,
        error: formatWorkerError(error),
    });
});

// Log worker-level errors, usually connection/runtime-level issues.
monthlyReviewWorker.on("error", (error) => {
    console.error("Monthly review worker error:", formatWorkerError(error));
});
